apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bernardoborges-flask-api
  namespace: default
  labels:
    app: bernardoborges-flask-api
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
