apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-react-client
  namespace: bernardoborges
  labels:
    app: spotify-react-client
spec:
  selector:
    matchLabels:
      app: spotify-react-client
  replicas: 1
  template:
    metadata:
      labels:
        app: spotify-react-client
    spec:
      containers:
        - name: spotify-react-client
          image: bernborgess/spotify-react-client:1.1
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: VITE_API_URL
              value: http://localhost
            - name: VITE_API_PORT
              value: "32172"
          ports:
            - containerPort: 32472
              name: spotify-react-client
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: spotify-react-client-service
  namespace: bernardoborges
spec:
  selector:
    app: spotify-react-client
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: spotify-react-client-service
      protocol: TCP
      port: 32472
      targetPort: 32472
      nodePort: 32472
