apiVersion: batch/v1
kind: Job
metadata:
  name: spotify-model-gen
  namespace: bernardoborges
  labels:
    app: spotify-model-gen
spec:
  template:
    metadata:
      name: spotify-model-gen
      labels:
        app: spotify-model-gen
    spec:
      containers:
        - name: spotify-model-gen
          image: bernborgess/spotify-model-gen:1.2
          command: ["python3", "gen.py"]
          env:
            - name: VOLUME_DIR
              value: /home/bernardoborges/project2-pv
            - name: DATASET_FILENAME
              value: 2023_spotify_ds1.csv
          volumeMounts:
            - name: project2-pv-bernardoborges
              mountPath: /home/bernardoborges/project2-pv
      volumes:
        - name: project2-pv-bernardoborges
          hostPath:
            path: /home/bernardoborges/project2-pv
      restartPolicy: OnFailure
      dnsPolicy: ClusterFirst
