apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc-bernardoborges
  namespace: bernardoborges
  labels:
    app: project2-pvc-bernardoborges
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
