apiVersion: batch/v1
kind: Job
metadata:
  name: spotify-model-gen
  namespace: bernardoborges
  labels:
    app: spotify-model-gen
spec:
  template:
    metadata:
      name: spotify-model-gen
      labels:
        app: spotify-model-gen
    spec:
      containers:
        - name: spotify-model-gen
          image: bernborgess/spotify-model-gen:0.5
          env:
            - name: DATASET
              value: "dummy-where-is-data"
            - name: OUTPUT_DIR
              value: "dummy-output-model"
          volumeMounts:
            - name: project2-pv-bernardoborges
              mountPath: /home/bernardoborges/project2-pv
      volumes:
        - name: project2-pv-bernardoborges
          hostPath:
            path: /home/bernardoborges/project2-pv
      restartPolicy: OnFailure
      dnsPolicy: ClusterFirst
  backoffLimit: 4
