apiVersion: batch/v1
kind: Job
metadata:
  name: spotify-model-gen
  namespace: bernardoborges
  labels:
    app: spotify-model-gen
spec:
  template:
    metadata:
      name: spotify-model-gen
      labels:
        app: spotify-model-gen
    spec:
      containers:
        - name: spotify-model-gen
          image: bernborgess/spotify-model-gen:0.5
          command: ["python3", "gen.py"]
          env:
            - name: DATASET
              value: "/?"
            - name: OUTPUT_DIR
              value: /home/bernardoborges/project2-pv
          volumeMounts:
            - name: project2-pv-bernardoborges
              mountPath: /home/bernardoborges/project2-pv
            - name: dataset-volume
              mountPath: /home/datasets
      volumes:
        - name: project2-pv-bernardoborges
          hostPath:
            path: /home/bernardoborges/project2-pv
        - name: dataset-volume
          hostPath:
            path: /home/datasets
            type: Directory
      restartPolicy: OnFailure
      dnsPolicy: ClusterFirst
